# Generated by Django 6.0 on 2025-12-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feerecord',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='feerecord',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='verification_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending Verification')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending Verification')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bus_route',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='monthly_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student')], default='student', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together={('student_profile', 'month')},
        ),
    ]
