# Generated by Django 6.0 on 2025-12-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feerecord_options_feerecord_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bus_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
